### ISSUE TITLE
How to use this library with the CTC-DRA-10-R2 DMX shield

### ISSUE THREAD

**Issue by antoniomechas** [claudeheintz/LXSAMD21DMX#3]
Hello,
I'm developing a system to control a LED strips with FASTLED receiving DMX in a Arduino Zero with the CTC-DRA-10-R2 DMX shield: https://www.dfrobot.com/product-984.html.

I would greatly appreciate any tips in how to use this library with the mentioned DMX shield. I have been reading along the code, but I'm not able to find what to modify.

Many thanks,
Antonio.

**Comment by claudeheintz** [comment]
Hi,

Understanding how to configure the various serial communication (sercom) possibilities on the SAMD21 is a little confusing at first.  Fortunately, Adafruit has an excellent article https://learn.adafruit.com/using-atsamd21-sercom-to-add-more-spi-i2c-serial-ports/overview that explains how it works pretty well.  (I wish I had this article when I was originally writing this library instead of having to work it out for myself...)

I updated the library header file with a section of alternate macros that should allow it to work with pins 3 and 4 on an Arduino Zero.  Unfortunately, I don't have an Arduino Zero to test.  All I can do is verify that the code compiles correctly. 

There are 9 #define macros that control which sercom, pins and pads the library uses.

The way LXSAMD21DMX.h works now is that if you uncomment line 506, you will switch to using sercom2 and pins 3 and 4.

I hope this helps.  Please let me know if it works for you.

-Claude Heintz

**Comment by antoniomechas** [comment]
Hello Claude,
I downloaded your changes and now it is working like a charm, many thanks for your kick response.
I'm using the shiled just to receive DMX, and so far it is working perfectly with a RobotDyn M0.
Now I need to add the FastLED library and see if I can control a LED strip from DMX (I read that fastLED needs to disable interrupts, so maybe it will cause some drops in the DMX data)
Thanks!
Antonio.

**Comment by claudeheintz** [comment]
I'm glad its working now.

**Comment by maddice** [comment]
Hello Claude and Antonio

I have been working with the Arduino Leonardo and Uno board and have had success with FastLed library standalone.  I have a DMX Shield that I have been trying to use and have not had success using an Enttec USB PRO with QLCPlus controlling the board pair.  I have WS2812B LED strips that I plan to use for a theater show.

I am new to Arduino, I've looked at the various libraries out there but cannot decipher what I am setting up incorrectly.  Any information or assistance would be greatly appreciated.

Thank you
Mike Addice

**Comment by antoniomechas** [comment]
Hello Mike,
I started using Arduino, but I changed to Teensy because it is far better
for LED control.
I'm using a Teensy 3.2 with a DMX Shield (see attached picture).
I had to do a small PCB to adapt the DMX Shield to the teensy.
If you need to receive DMX, connecting the RX of the teensy (pin 0) to the
pin 3 of the DMX shield will do the trick.
I'm using the DMX library from https://github.com/jimparis/DmxReceiver
For the ws2812B leds, I recommend you using the teensy 3.2 and the
OCTOWS2811 library (https://www.pjrc.com/teensy/td_libs_OctoWS2811.html),
is the best for driving LED strips.
Antonio.

**Comment by maddice** [comment]
Thank you for the information.  Did you use a standard DMX shield or did you build one? I also found this site - http://lights4music.com/instructions.html, shows a DIY board.
Were you able to use the FASTLED library over DMX.  There are sequences that I need to use for my project.

**Comment by rafic98** [comment]
hello, I need help, i dont know how to write a code so i can let a light with address 2 turn on, how is that possible, i am using arduino uno and CTC-DRA-10-R2 shield.

**Comment by fostiras** [comment]
> hello, I need help, i dont know how to write a code so i can let a light with address 2 turn on, how is that possible, i am using arduino uno and CTC-DRA-10-R2 shield.

This Library is for a SAMD21 chip which is found on an Arduino Zero. You have to use a DMX library for Arduino Uno like the mathertel /DMXSerial library. Then simply load a receiver example : https://github.com/mathertel/DMXSerial/blob/master/examples/DmxSerialRecv/DmxSerialRecv.ino  . The example scetch uses 3 channels for a RGB light, you can just use one channel , the Green one at address 2.
